# Generated by Django 4.0.1 on 2022-01-11 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_delete_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
    ]
